apiVersion: v1
data:
  vhost.conf: |
    ServerName "${HOSTNAME}"

    <VirtualHost *:8080>

        # The OIDC service provider. For EBRAINS, it is here:
        OIDCProviderMetadataURL "${OIDC_ISSUER}/.well-known/openid-configuration"
        OIDCClientID "${OIDC_CLIENT_ID}"
        OIDCClientSecret "${OIDC_CLIENT_SECRET}"

        # /redirect_uri is used to authenticate you.
        # It will be consumed by Apache
        # this request will not be forwarded to your application.
        OIDCRedirectURI "${HOSTNAME}/redirect_uri"
        OIDCCryptoPassphrase "${OIDC_CRYPTO_PASSPHRASE}"

        # Interval in seconds after which the session will be invalidated when no interaction has occurred.
        # When not defined, the default is 300 seconds.
        OIDCSessionInactivityTimeout 3600

        # Maximum duration of the application session
        # When not defined the default is 8 hours (3600 * 8 seconds).
        # When set to 0, the session duration will be set equal to the expiry time of the ID token.
        # NB: this can be overridden on a per-OP basis in the .conf file using the key: session_max_duration
        OIDCSessionMaxDuration 0

        # Time to live in seconds for state parameter
        # i.e. the interval in which the authorization request.
        OIDCStateTimeout 7200

        # Clean up old cookie states if needed.
        OIDCStateMaxNumberOfCookies 5 true

        <Location "/">
            AuthType openid-connect
            Require valid-user
        </Location>

        # This handles proxying.
        ProxyAddHeaders On
        ProxyRequests Off
        ProxyPreserveHost On

        # special url used by mod oidc, do not proxy
        ProxyPass /redirect_uri !

        #
        # forward traffic to services
        #

        # NEST Simulator
        ProxyPass /nest http://${NEST_SIMULATOR_SERVICE_HOST}:52425/
        ProxyPassReverse /nest http://${NEST_SIMULATOR_SERVICE_HOST}:52425/

        # NEST Desktop
        ProxyPass / http://${NEST_DESKTOP_V3_SERVICE_HOST}:54286/
        ProxyPassReverse / http://${NEST_DESKTOP_V3_SERVICE_HOST}:54286/
    </VirtualHost>
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{"vhost.conf":"ServerName









      \"${HOSTNAME}\"\n\n\u003cVirtualHost *:8080\u003e\n\n    # The OIDC
      service









      provider. For EBRAINS, it is here:\n    OIDCProviderMetadataURL









      \"${OIDC_ISSUER}/.well-known/openid-configuration\"\n    OIDCClientID









      \"${OIDC_CLIENT_ID}\"\n    OIDCClientSecret
      \"${OIDC_CLIENT_SECRET}\"\n\n    #









      /redirect_uri is used to authenticate you.\n    # It will be consumed by









      Apache\n    # this request will not be forwarded to your application.\n   









      OIDCRedirectURI \"${HOSTNAME}/redirect_uri\"\n    OIDCCryptoPassphrase









      \"${OIDC_CRYPTO_PASSPHRASE}\"\n\n    # Interval in seconds after which the









      session will be invalidated when no interaction has occurred.\n    # When
      not









      defined, the default is 300 seconds.\n    OIDCSessionInactivityTimeout









      3600\n\n    # Maximum duration of the application session\n    # When not









      defined the default is 8 hours (3600 * 8 seconds).\n    # When set to 0,
      the









      session duration will be set equal to the expiry time of the ID
      token.\n    #









      NB: this can be overridden on a per-OP basis in the .conf file using the
      key:









      session_max_duration\n    OIDCSessionMaxDuration 0\n\n    # Time to live
      in









      seconds for state parameter\n    # i.e. the interval in which the









      authorization request.\n    OIDCStateTimeout 7200\n\n    # Clean up old
      cookie









      states if needed.\n    OIDCStateMaxNumberOfCookies 5 true\n\n   









      \u003cLocation \"/\"\u003e\n        AuthType openid-connect\n       
      Require









      valid-user\n    \u003c/Location\u003e\n\n    # This handles proxying.\n   









      ProxyAddHeaders On\n    ProxyRequests Off\n    ProxyPreserveHost On\n\n   
      #









      special url used by mod oidc, do not proxy\n    ProxyPass /redirect_uri









      !\n\n    #\n    # forward traffic to services\n    #\n\n    # NEST









      Simulator\n    ProxyPass /nest









      http://${NEST_SIMULATOR_SERVICE_HOST}:52425/\n    ProxyPassReverse /nest









      http://${NEST_SIMULATOR_SERVICE_HOST}:52425/\n\n    # NEST Desktop\n   









      ProxyPass / http://${NEST_DESKTOP_SERVICE_HOST}:54286/\n   
      ProxyPassReverse /









      http://${NEST_DESKTOP_SERVICE_HOST}:54286/\n\u003c/VirtualHost\u003e\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"apache2-oidc","namespace":"nest-desktop"}}
  creationTimestamp: '2024-12-02T12:06:01Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:vhost.conf: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
      manager: agent
      operation: Update
      time: '2024-12-03T07:08:39Z'
  name: apache2-oidc-v3
  namespace: nest-desktop
  resourceVersion: '393359141'
  uid: 78bc5f54-4869-4750-85bf-039d69d233e4
