apiVersion: v1
data:
  OIDC_CRYPTO_PASSPHRASE: It should be a random value.
  OIDC_ISSUER: https://iam.ebrains.eu/auth/realms/hbp
kind: ConfigMap
metadata:
  creationTimestamp: '2024-12-02T18:30:02Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:OIDC_CRYPTO_PASSPHRASE: {}
          f:OIDC_ISSUER: {}
      manager: agent
      operation: Update
      time: '2024-12-02T18:30:02Z'
  name: iam.ebrains.eu
  namespace: nest-desktop
  resourceVersion: '392873532'
  uid: a129b087-02b8-4ad8-8eb6-500d947cdd5e
