apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2023-10-26T13:05:04Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2023-10-26T13:05:04Z'
  name: apache2-oidc
  namespace: nest-dev
  resourceVersion: '205307976'
  uid: 9a008c65-2d5c-4493-8766-882a14466d05
spec:
  clusterIP: 10.43.194.34
  clusterIPs:
    - 10.43.194.34
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    io.kompose.service: apache2-oidc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
