apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2023-08-08T08:13:03Z'
  labels:
    io.kompose.service: nest-simulator
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:io.kompose.service: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":52425,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2023-08-08T08:13:03Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:ports:
            k:{"port":52425,"protocol":"TCP"}:
              f:name: {}
            k:{"port":52426,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:sessionAffinity: {}
      manager: agent
      operation: Update
      time: '2024-11-22T08:10:32Z'
  name: nest-simulator
  namespace: nest-dev
  resourceVersion: '410140006'
  uid: b21c73ab-0a8b-4612-baca-849748cc5760
spec:
  clusterIP: 10.43.66.180
  clusterIPs:
    - 10.43.66.180
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: nest-simulator
      port: 52425
      protocol: TCP
      targetPort: 52425
    - name: nestml
      port: 52426
      protocol: TCP
      targetPort: 52426
  selector:
    io.kompose.service: nest-simulator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
