apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/selected-node: rke2-1-worker-07
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: '2024-09-26T08:22:04Z'
  finalizers:
    - kubernetes.io/pvc-protection
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: agent
      operation: Update
      time: '2024-09-26T08:22:04Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:volume.kubernetes.io/selected-node: {}
      manager: kube-scheduler
      operation: Update
      time: '2024-09-26T08:22:04Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
            f:volume.kubernetes.io/storage-provisioner: {}
        f:spec:
          f:volumeName: {}
      manager: kube-controller-manager
      operation: Update
      time: '2024-09-26T08:22:06Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2024-09-26T08:22:06Z'
  name: nestmlmodules
  namespace: nest-desktop
  resourceVersion: '322673653'
  uid: dd0d1ee2-aacc-4c99-a1fe-6188ec7a809c
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-1
  volumeMode: Filesystem
  volumeName: pvc-dd0d1ee2-aacc-4c99-a1fe-6188ec7a809c
status:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  capacity:
    storage: 1Gi
  phase: Bound
