apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nest-desktop
  name: nest-desktop
  namespace: nest-dev
spec:
  selector:
    matchLabels:
      io.kompose.service: nest-desktop
  template:
    metadata:
      labels:
        io.kompose.service: nest-desktop
      name: nest-desktop
      namespace: nest-dev
    spec:
      containers:
        - env:
            - name: NEST_SIMULATOR_URL
              value: https://nest-desktop.helmholtz-cloud.desy.de/nest
          image: docker-registry.ebrains.eu/nest/nest-desktop:3.3
          imagePullPolicy: IfNotPresent
          name: nest-desktop
      volumes:
        - configMap:
            defaultMode: 420
            name: apache2-oidc
          name: volume-apache2-config
