apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2024-05-16T13:16:04Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":11428,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":52425,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":52426,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":54286,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:sessionAffinityConfig:
            .: {}
            f:clientIP:
              .: {}
              f:timeoutSeconds: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2024-12-06T21:46:54Z'
  name: nest-desktop-dev
  namespace: nest-desktop
  resourceVersion: '406802580'
  uid: cf0ce6f5-5233-47a6-adc2-a9760511d472
spec:
  clusterIP: 10.43.139.62
  clusterIPs:
    - 10.43.139.62
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: auth
      port: 8080
      protocol: TCP
      targetPort: auth
    - name: frontend
      port: 54286
      protocol: TCP
      targetPort: frontend
    - name: nest
      port: 52425
      protocol: TCP
      targetPort: nest
    - name: nestml
      port: 52426
      protocol: TCP
      targetPort: nestml
    - name: norse
      port: 11428
      protocol: TCP
      targetPort: norse
  selector:
    io.kompose.service: nest-desktop-dev
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
  type: ClusterIP
status:
  loadBalancer: {}
