apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2023-11-03T12:19:37Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":52425,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":54286,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:sessionAffinityConfig:
            .: {}
            f:clientIP:
              .: {}
              f:timeoutSeconds: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2024-12-06T22:12:02Z'
  name: nest-desktop
  namespace: nest-desktop
  resourceVersion: '406893917'
  uid: c8955de4-1272-4e7e-953f-3de02f1a3a82
spec:
  clusterIP: 10.43.154.6
  clusterIPs:
    - 10.43.154.6
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: auth
      port: 8080
      protocol: TCP
      targetPort: auth
    - name: frontend
      port: 54286
      protocol: TCP
      targetPort: frontend
    - name: nest
      port: 52425
      protocol: TCP
      targetPort: nest
  selector:
    io.kompose.service: nest-desktop
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
  type: ClusterIP
status:
  loadBalancer: {}
