apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2024-12-02T13:49:15Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":52425,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":54286,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:sessionAffinityConfig:
            .: {}
            f:clientIP:
              .: {}
              f:timeoutSeconds: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2024-12-06T22:11:45Z'
  name: nest-desktop-v3
  namespace: nest-desktop
  resourceVersion: '406892855'
  uid: 40b01edb-2bb0-47eb-9399-3fbc5a7de61c
spec:
  clusterIP: 10.43.221.141
  clusterIPs:
    - 10.43.221.141
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: auth
      port: 8080
      protocol: TCP
      targetPort: auth
    - name: frontend
      port: 54286
      protocol: TCP
      targetPort: frontend
    - name: nest
      port: 52425
      protocol: TCP
      targetPort: nest
  selector:
    io.kompose.service: nest-desktop-v3
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
  type: ClusterIP
status:
  loadBalancer: {}
