apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC4TCCAcmgAwIBAgIBADANBgkqhkiG9w0BAQsFADASMRAwDgYDVQQDEwdrdWJl
    LWNhMB4XDTIyMDYyNzA4MTczM1oXDTMyMDYyNDA4MTczM1owEjEQMA4GA1UEAxMH
    a3ViZS1jYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMm0WCRzJy2w
    dVqf96b9WokrhV4fJUYD7ivnYKlGd42SNlmyj1LLhnyTdDM9q7j5+THWWQ8Zf+WQ
    IlyCeJlqL0aIFInANBPww1sY5rnkPzo6gMTjg8oFVwFHz57ZKCHhHiwJctUTaSwv
    py2YwRTrAANDllWIKCBQ3lXnnLVSdeCwzjZ/6e8z9UurE4MDhq+Q2stj1fzf5O4S
    WyG/a/Ltqb3AVFddF+e/oAMHGjmAmMeiE9kkvAboasM901dHpF+IXdSL+AkrozPC
    rX860GUcyXG9i+V4Kx3wy4EIyRq2KwfvDgXLoayq0wUVkBRcaNUDjo7mtLPPKXw/
    eV+q6B20400CAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMB
    Af8wHQYDVR0OBBYEFHUa7l96zZ2OUOnFAoajbo23+c04MA0GCSqGSIb3DQEBCwUA
    A4IBAQCJstwtuK3HKaVfoysWk/D80sbt9ihFXWShDxOeuS6pg2iTkGWxOOKOMhHM
    wQQYmeElZMzPR9RvEJ2XwOEKtcdXjsPb/l7zvQzvOeFakWDa1fGAcorbWs9Xd+K1
    WlYOp6/+yJ7a7BEznJquYjKvdgiStOtpMwl+Jy7NTukGf49DEL/J4yvwS/1DLvjd
    En9RGUnrJ8cdNrSYBn58q0Okq6nhNs6oQN9XtGzXNm9o219+mUmJmLq4t56qSxUL
    okW2fiSJ0WDCpLdyON+AvMdK7ddPxaF+jeqinJp/2Sl04BZ3+y3Plym48slXF3zX
    Kb7xU+RUQoYcisZnjCEBPt7khTdT
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: >-
      Contains a CA bundle that can be used to verify the kube-apiserver when
      using internal endpoints such as the internal service IP or
      kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  creationTimestamp: '2023-07-26T11:21:03Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca.crt: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubernetes.io/description: {}
      manager: kube-controller-manager
      operation: Update
      time: '2023-07-26T11:21:03Z'
  name: kube-root-ca.crt
  namespace: nest-dev
  resourceVersion: '162327231'
  uid: 1ea3dd7d-10b2-4bb1-9612-cf3fd26771a4
