apiVersion: v1
data:
  HOSTNAME: https://nest-desktop.helmholtz-cloud.desy.de
  OIDC_CLIENT_ID: nest-desktop-dev
  OIDC_CRYPTO_PASSPHRASE: It should be a random value.
  OIDC_ISSUER: https://login-dev.helmholtz.de/oauth2
kind: ConfigMap
metadata:
  creationTimestamp: '2023-10-11T07:12:57Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:HOSTNAME: {}
          f:OIDC_CLIENT_ID: {}
          f:OIDC_CRYPTO_PASSPHRASE: {}
          f:OIDC_ISSUER: {}
      manager: agent
      operation: Update
      time: '2023-10-11T07:12:57Z'
  name: oidc-env
  namespace: nest-dev
  resourceVersion: '197878328'
  uid: 0c0491f5-a0fd-44d1-a478-0bc0e90d72cc
