apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '55'
  creationTimestamp: '2024-05-16T13:11:42Z'
  generation: 69
  labels:
    io.kompose.service: nest-desktop-dev
    workload.user.cattle.io/workloadselector: apps.deployment-nest-desktop-nest-desktop-dev
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations: {}
          f:labels:
            .: {}
            f:io.kompose.service: {}
            f:workload.user.cattle.io/workloadselector: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:cattle.io/timestamp: {}
                f:kubectl.kubernetes.io/restartedAt: {}
              f:labels:
                .: {}
                f:io.kompose.network/nest-desktop-default: {}
                f:io.kompose.service: {}
                f:workload.user.cattle.io/workloadselector: {}
              f:name: {}
              f:namespace: {}
            f:spec:
              f:containers:
                k:{"name":"nest-desktop"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"NEST_SIMULATOR_URL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"NESTML_SERVER_ENABLED"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"NESTML_SERVER_URL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"NORSE_SIMULATOR_URL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:allowPrivilegeEscalation: {}
                    f:privileged: {}
                    f:readOnlyRootFilesystem: {}
                    f:runAsNonRoot: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
      manager: agent
      operation: Update
      time: '2024-11-28T12:36:56Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2024-11-28T12:36:57Z'
  name: nest-desktop-dev
  namespace: nest-desktop
  resourceVersion: '388860854'
  uid: 822e9cb8-5b6d-45f7-9e9f-5fd72bf17c5f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-nest-desktop-nest-desktop-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2024-11-28T12:36:56Z'
        kubectl.kubernetes.io/restartedAt: '2023-11-07T22:50:36+02:00'
      creationTimestamp: null
      labels:
        io.kompose.network/nest-desktop-default: 'true'
        io.kompose.service: nest-desktop-dev
        workload.user.cattle.io/workloadselector: apps.deployment-nest-desktop-nest-desktop-dev
      name: nest-desktop-dev
      namespace: nest-desktop
    spec:
      containers:
        - env:
            - name: NEST_SIMULATOR_URL
              value: https://nest-desktop.apps.tc.humanbrainproject.eu/nest
            - name: NORSE_SIMULATOR_URL
              value: https://nest-desktop.apps.tc.humanbrainproject.eu/norse
            - name: NESTML_SERVER_URL
              value: https://nest-desktop.apps.tc.humanbrainproject.eu/nestml
            - name: NESTML_SERVER_ENABLED
              value: '1'
          image: docker-registry.ebrains.eu/nest/nest-desktop:4.0
          imagePullPolicy: Always
          name: nest-desktop
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2024-11-06T09:32:23Z'
      lastUpdateTime: '2024-11-06T09:32:23Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2024-05-16T13:11:42Z'
      lastUpdateTime: '2024-11-28T12:36:57Z'
      message: ReplicaSet "nest-desktop-dev-58d47c487c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 69
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
