apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2024-12-02T13:49:15Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":54286,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2024-12-02T13:49:15Z'
  name: nest-desktop-v3
  namespace: nest-desktop
  resourceVersion: '393388505'
  uid: 40b01edb-2bb0-47eb-9399-3fbc5a7de61c
spec:
  clusterIP: 10.43.221.141
  clusterIPs:
    - 10.43.221.141
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 54286
      protocol: TCP
      targetPort: 54286
  selector:
    io.kompose.service: nest-desktop-v3
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
