apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2024-09-26T07:37:46Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":52425,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":52426,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2024-11-06T11:55:31Z'
  name: nest-simulator-dev
  namespace: nest-desktop
  resourceVersion: '366020309'
  uid: 5440c2f0-5b8d-4fb2-be6e-f7c62ad10f20
spec:
  clusterIP: 10.43.163.93
  clusterIPs:
    - 10.43.163.93
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: nest-simulator
      port: 52425
      protocol: TCP
      targetPort: 52425
    - name: nestml
      port: 52426
      protocol: TCP
      targetPort: 52426
  selector:
    io.kompose.service: nest-simulator-dev
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
