apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2024-05-16T13:16:04Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":54286,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:sessionAffinityConfig:
            .: {}
            f:clientIP:
              .: {}
              f:timeoutSeconds: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2024-11-07T16:35:30Z'
  name: nest-desktop-dev
  namespace: nest-desktop
  resourceVersion: '367118243'
  uid: cf0ce6f5-5233-47a6-adc2-a9760511d472
spec:
  clusterIP: 10.43.139.62
  clusterIPs:
    - 10.43.139.62
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: nest-desktop
      port: 54286
      protocol: TCP
      targetPort: 54286
  selector:
    io.kompose.service: nest-desktop-dev
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
  type: ClusterIP
status:
  loadBalancer: {}
