apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2023-11-03T12:19:37Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":54286,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2024-11-06T12:03:15Z'
  name: nest-desktop
  namespace: nest-desktop
  resourceVersion: '366025404'
  uid: c8955de4-1272-4e7e-953f-3de02f1a3a82
spec:
  clusterIP: 10.43.154.6
  clusterIPs:
    - 10.43.154.6
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 54286
      protocol: TCP
      targetPort: 54286
  selector:
    io.kompose.service: nest-desktop
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
