apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2023-11-03T12:20:40Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:allocateLoadBalancerNodePorts: {}
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":52425,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":52426,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:sessionAffinityConfig:
            .: {}
            f:clientIP:
              .: {}
              f:timeoutSeconds: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2024-11-07T16:02:01Z'
  name: nest-simulator
  namespace: nest-desktop
  resourceVersion: '367089457'
  uid: 90cc03bd-c464-46df-91c1-c3e9df374dea
spec:
  clusterIP: 10.43.46.230
  clusterIPs:
    - 10.43.46.230
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: nest-simulator
      port: 52425
      protocol: TCP
      targetPort: 52425
    - name: nestml
      port: 52426
      protocol: TCP
      targetPort: 52426
  selector:
    io.kompose.service: nest-simulator
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
  type: ClusterIP
status:
  loadBalancer: {}
