apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2024-05-16T13:02:59Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:allocateLoadBalancerNodePorts: {}
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2024-11-07T16:04:19Z'
  name: nest-desktop-apps-ebrains-eu
  namespace: nest-desktop
  resourceVersion: '367090915'
  uid: a1a6c166-9ea9-488f-9a66-6f7da47b38ec
spec:
  clusterIP: 10.43.47.237
  clusterIPs:
    - 10.43.47.237
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    io.kompose.service: nest-desktop.apps.ebrains.eu
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
