apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2023-08-08T08:14:02Z'
  labels:
    io.kompose.service: nest-desktop
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2023-08-08T08:14:02Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:io.kompose.service: {}
        f:spec:
          f:ports:
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":52425,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":54286,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:sessionAffinityConfig:
            .: {}
            f:clientIP:
              .: {}
              f:timeoutSeconds: {}
      manager: agent
      operation: Update
      time: '2024-12-06T22:11:28Z'
  name: nest-desktop
  namespace: nest-dev
  resourceVersion: '417518530'
  uid: 8b6c2391-8213-4691-a794-3ebf439142e3
spec:
  clusterIP: 10.43.232.246
  clusterIPs:
    - 10.43.232.246
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: auth
      port: 8080
      protocol: TCP
      targetPort: auth
    - name: frontend
      port: 54286
      protocol: TCP
      targetPort: frontend
    - name: nest
      port: 52425
      protocol: TCP
      targetPort: nest
  selector:
    io.kompose.service: nest-desktop
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
  type: ClusterIP
status:
  loadBalancer: {}
