apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '8'
    field.cattle.io/publicEndpoints: 'null'
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.30.0 (HEAD)
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kompose.cmd":"kompose
      convert -f docker-compose.yml","kompose.version":"1.30.0
      (HEAD)"},"creationTimestamp":null,"labels":{"io.kompose.service":"nest-simulator"},"name":"nest-simulator","namespace":"nest-dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"io.kompose.service":"nest-simulator"}},"strategy":{},"template":{"metadata":{"annotations":{"kompose.cmd":"kompose
      convert -f docker-compose.yml","kompose.version":"1.30.0
      (HEAD)"},"creationTimestamp":null,"labels":{"io.kompose.network/nest-desktop-default":"true","io.kompose.service":"nest-simulator"}},"spec":{"containers":[{"env":[{"name":"NEST_CONTAINER_MODE","value":"nest-server"}],"image":"docker-registry.ebrains.eu/nest/nest-simulator:3.4","name":"nest-simulator","ports":[{"containerPort":52425,"hostPort":52425,"protocol":"TCP"}],"resources":{}}],"restartPolicy":"Always"}}},"status":{}}
  creationTimestamp: '2023-08-08T08:10:31Z'
  generation: 46
  labels:
    io.kompose.service: nest-simulator
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kompose.cmd: {}
            f:kompose.version: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:io.kompose.service: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:kompose.cmd: {}
                f:kompose.version: {}
              f:labels:
                .: {}
                f:io.kompose.network/nest-desktop-default: {}
                f:io.kompose.service: {}
            f:spec:
              f:containers:
                k:{"name":"nest-simulator"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"NEST_CONTAINER_MODE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2023-08-08T08:10:31Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:field.cattle.io/publicEndpoints: {}
        f:spec:
          f:replicas: {}
          f:template:
            f:metadata:
              f:annotations:
                f:cattle.io/timestamp: {}
              f:namespace: {}
            f:spec:
              f:containers:
                k:{"name":"nest-simulator"}:
                  f:image: {}
                  f:resources:
                    f:limits:
                      .: {}
                      f:memory: {}
                k:{"name":"nestml"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"NEST_CONTAINER_MODE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources:
                    .: {}
                    f:limits:
                      .: {}
                      f:memory: {}
                    f:requests:
                      .: {}
                      f:memory: {}
                  f:securityContext:
                    .: {}
                    f:allowPrivilegeEscalation: {}
                    f:privileged: {}
                    f:readOnlyRootFilesystem: {}
                    f:runAsNonRoot: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
      manager: agent
      operation: Update
      time: '2024-11-22T08:33:53Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2024-11-22T08:33:54Z'
  name: nest-simulator
  namespace: nest-dev
  resourceVersion: '410148403'
  uid: b4e61cac-f75b-4777-8dfd-1385614d6da1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: nest-simulator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2023-11-03T12:21:37Z'
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/nest-desktop-default: 'true'
        io.kompose.service: nest-simulator
      namespace: nest-dev
    spec:
      containers:
        - env:
            - name: NEST_CONTAINER_MODE
              value: nest-server
          image: nest/nest-simulator:3.8
          imagePullPolicy: IfNotPresent
          name: nest-simulator
          resources:
            limits:
              memory: 8000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - env:
            - name: NEST_CONTAINER_MODE
              value: nestml-server
          image: nest/nest-simulator:3.8
          imagePullPolicy: IfNotPresent
          name: nestml
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2023-08-08T08:10:31Z'
      lastUpdateTime: '2024-09-26T14:06:48Z'
      message: ReplicaSet "nest-simulator-ff65b67b7" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2024-11-21T13:05:52Z'
      lastUpdateTime: '2024-11-21T13:05:52Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 46
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
