apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '23'
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["10.43.73.212"],"port":443,"protocol":"HTTPS","serviceName":"nest-dev:nest-desktop","ingressName":"nest-dev:nest","hostname":"nest-desktop.helmholtz-cloud.desy.de","path":"/","allNodes":true}]
  creationTimestamp: '2023-08-08T08:10:45Z'
  generation: 120
  labels:
    io.kompose.service: nest-desktop
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations: {}
          f:labels:
            .: {}
            f:io.kompose.service: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:io.kompose.service: {}
            f:spec:
              f:containers:
                k:{"name":"nest-desktop"}:
                  .: {}
                  f:env: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2023-08-08T08:10:45Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:field.cattle.io/publicEndpoints: {}
        f:spec:
          f:replicas: {}
          f:template:
            f:metadata:
              f:namespace: {}
            f:spec:
              f:containers:
                k:{"name":"nest-desktop"}:
                  f:env:
                    k:{"name":"NEST_SIMULATOR_URL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"NESTML_SERVER_URL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":54286,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
              f:volumes:
                .: {}
                k:{"name":"volume-apache2-config"}:
                  .: {}
                  f:configMap:
                    .: {}
                    f:defaultMode: {}
                    f:name: {}
                  f:name: {}
      manager: agent
      operation: Update
      time: '2024-12-06T22:10:35Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2024-12-06T22:10:35Z'
  name: nest-desktop
  namespace: nest-dev
  resourceVersion: '417518206'
  uid: ee4102d8-6732-409a-94aa-35372c77863f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: nest-desktop
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nest-desktop
      namespace: nest-dev
    spec:
      containers:
        - env:
            - name: NEST_SIMULATOR_URL
              value: https://nest-desktop.helmholtz-cloud.desy.de/nest
            - name: NESTML_SERVER_URL
              value: https://nest-desktop.helmholtz-cloud.desy.de/nestml
          image: nest/nest-desktop:4.0
          imagePullPolicy: Always
          name: nest-desktop
          ports:
            - containerPort: 54286
              name: frontend
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: apache2-oidc
          name: volume-apache2-config
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2024-12-06T22:09:01Z'
      lastUpdateTime: '2024-12-06T22:09:01Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2023-08-08T08:10:45Z'
      lastUpdateTime: '2024-12-06T22:10:07Z'
      message: ReplicaSet "nest-desktop-5d666ffd" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 120
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
